vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.autoindent = true
vim.opt.si = true
vim.opt.tabstop = 4
vim.opt.shiftwidth= 4
vim.opt.expandtab = true
vim.opt.softtabstop = 4
vim.opt.termguicolors = true
vim.opt.hlsearch = false
vim.opt.incsearch = true
vim.opt.guicursor = ""
vim.opt.smartindent = true
vim.opt.updatetime = 50
vim.opt.colorcolumn =  "150"
